# Generated by Django 4.1 on 2022-09-14 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mitmlearning', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='mitmlearning.category', verbose_name='カテゴリ'),
            preserve_default=False,
        ),
    ]
