# Generated by Django 4.1 on 2022-09-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitmlearning', '0003_term_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='画像'),
        ),
    ]
