# Generated by Django 4.1.2 on 2022-10-11 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mitmlearning', '0004_term_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='term',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
